(function() {var implementors = {};
implementors["rustorm"] = ["impl <a class='trait' href='https://doc.rust-lang.org/nightly/core/convert/trait.From.html' title='core::convert::From'>From</a>&lt;<a class='struct' href='https://sfackler.github.io/r2d2/doc/v0.7.0/r2d2/struct.InitializationError.html' title='r2d2::InitializationError'>InitializationError</a>&gt; for <a class='enum' href='rustorm/database/enum.DbError.html' title='rustorm::database::DbError'>DbError</a>","impl <a class='trait' href='https://doc.rust-lang.org/nightly/core/convert/trait.From.html' title='core::convert::From'>From</a>&lt;<a class='enum' href='rustorm/platform/enum.PlatformError.html' title='rustorm::platform::PlatformError'>PlatformError</a>&gt; for <a class='enum' href='rustorm/database/enum.DbError.html' title='rustorm::database::DbError'>DbError</a>","impl <a class='trait' href='https://doc.rust-lang.org/nightly/core/convert/trait.From.html' title='core::convert::From'>From</a>&lt;<a class='enum' href='https://doc.rust-lang.org/regex/regex/error/enum.Error.html' title='regex::error::Error'>RegexError</a>&gt; for <a class='enum' href='rustorm/database/enum.DbError.html' title='rustorm::database::DbError'>DbError</a>","impl <a class='trait' href='https://doc.rust-lang.org/nightly/core/convert/trait.From.html' title='core::convert::From'>From</a>&lt;<a class='enum' href='https://sfackler.github.io/rust-postgres/doc/v0.11.7/postgres/error/enum.Error.html' title='postgres::error::Error'>PgError</a>&gt; for <a class='enum' href='rustorm/database/enum.DbError.html' title='rustorm::database::DbError'>DbError</a>","impl <a class='trait' href='https://doc.rust-lang.org/nightly/core/convert/trait.From.html' title='core::convert::From'>From</a>&lt;<a class='enum' href='https://sfackler.github.io/rust-postgres/doc/v0.11.7/postgres/error/enum.ConnectError.html' title='postgres::error::ConnectError'>PgConnectError</a>&gt; for <a class='enum' href='rustorm/database/enum.DbError.html' title='rustorm::database::DbError'>DbError</a>","impl <a class='trait' href='https://doc.rust-lang.org/nightly/core/convert/trait.From.html' title='core::convert::From'>From</a>&lt;<a class='enum' href='https://sfackler.github.io/rust-postgres/doc/v0.11.7/postgres/error/enum.Error.html' title='postgres::error::Error'>PgError</a>&gt; for <a class='enum' href='rustorm/platform/enum.PlatformError.html' title='rustorm::platform::PlatformError'>PlatformError</a>","impl <a class='trait' href='https://doc.rust-lang.org/nightly/core/convert/trait.From.html' title='core::convert::From'>From</a>&lt;<a class='enum' href='https://sfackler.github.io/rust-postgres/doc/v0.11.7/postgres/error/enum.ConnectError.html' title='postgres::error::ConnectError'>PgConnectError</a>&gt; for <a class='enum' href='rustorm/platform/enum.PlatformError.html' title='rustorm::platform::PlatformError'>PlatformError</a>",];

            if (window.register_implementors) {
                window.register_implementors(implementors);
            } else {
                window.pending_implementors = implementors;
            }
        
})()
